<<<<<<< HEAD
version: "3.8"
services:
  api:
    environment:
      API_SERVICE_PORT: ${API_SERVICE_PORT}
      API_UID: ${API_UID}
      API_GID: ${API_GID}
      API_AUTH_JWT_SECRET: ${API_AUTH_JWT_SECRET}
      API_RUN_MIGRATIONS_ON_STARTUP: ${API_RUN_MIGRATIONS_ON_STARTUP}
      API_POSTGRES_USER: ${API_POSTGRES_USER}
      API_POSTGRES_PASSWORD: ${API_POSTGRES_PASSWORD}
      API_POSTGRES_DB: ${API_POSTGRES_DB}
      POSTGRES_API_SERVICE_PORT: ${POSTGRES_API_SERVICE_PORT}
      APP_SERVICE_PORT: ${APP_SERVICE_PORT}
      GEOPROCESSING_SERVICE_PORT: ${GEOPROCESSING_SERVICE_PORT}
      GEOPROCESSING_RUN_MIGRATIONS_ON_STARTUP: ${GEOPROCESSING_RUN_MIGRATIONS_ON_STARTUP}
      GEO_POSTGRES_USER: ${GEO_POSTGRES_USER}
      GEO_POSTGRES_PASSWORD: ${GEO_POSTGRES_PASSWORD}
      GEO_POSTGRES_DB: ${GEO_POSTGRES_DB}
      POSTGRES_GEO_SERVICE_PORT: ${POSTGRES_GEO_SERVICE_PORT}
  geoprocessing:
    environment:
      API_SERVICE_PORT: ${API_SERVICE_PORT}
      API_UID: ${API_UID}
      API_GID: ${API_GID}
      API_AUTH_JWT_SECRET: ${API_AUTH_JWT_SECRET}
      API_RUN_MIGRATIONS_ON_STARTUP: ${API_RUN_MIGRATIONS_ON_STARTUP}
      API_POSTGRES_USER: ${API_POSTGRES_USER}
      API_POSTGRES_PASSWORD: ${API_POSTGRES_PASSWORD}
      API_POSTGRES_DB: ${API_POSTGRES_DB}
      POSTGRES_API_SERVICE_PORT: ${POSTGRES_API_SERVICE_PORT}
      APP_SERVICE_PORT: ${APP_SERVICE_PORT}
      GEOPROCESSING_SERVICE_PORT: ${GEOPROCESSING_SERVICE_PORT}
      GEOPROCESSING_RUN_MIGRATIONS_ON_STARTUP: ${GEOPROCESSING_RUN_MIGRATIONS_ON_STARTUP}
      GEO_POSTGRES_USER: ${GEO_POSTGRES_USER}
      GEO_POSTGRES_PASSWORD: ${GEO_POSTGRES_PASSWORD}
      GEO_POSTGRES_DB: ${GEO_POSTGRES_DB}
      POSTGRES_GEO_SERVICE_PORT: ${POSTGRES_GEO_SERVICE_PORT}
  test-e2e-postgresql-api:
    environment:
      API_SERVICE_PORT: ${API_SERVICE_PORT}
      API_UID: ${API_UID}
      API_GID: ${API_GID}
      API_AUTH_JWT_SECRET: ${API_AUTH_JWT_SECRET}
      API_RUN_MIGRATIONS_ON_STARTUP: ${API_RUN_MIGRATIONS_ON_STARTUP}
      API_POSTGRES_USER: ${API_POSTGRES_USER}
      API_POSTGRES_PASSWORD: ${API_POSTGRES_PASSWORD}
      API_POSTGRES_DB: ${API_POSTGRES_DB}
      POSTGRES_API_SERVICE_PORT: ${POSTGRES_API_SERVICE_PORT}
      APP_SERVICE_PORT: ${APP_SERVICE_PORT}
      GEOPROCESSING_SERVICE_PORT: ${GEOPROCESSING_SERVICE_PORT}
      GEOPROCESSING_RUN_MIGRATIONS_ON_STARTUP: ${GEOPROCESSING_RUN_MIGRATIONS_ON_STARTUP}
      GEO_POSTGRES_USER: ${GEO_POSTGRES_USER}
      GEO_POSTGRES_PASSWORD: ${GEO_POSTGRES_PASSWORD}
      GEO_POSTGRES_DB: ${GEO_POSTGRES_DB}
      POSTGRES_GEO_SERVICE_PORT: ${POSTGRES_GEO_SERVICE_PORT}
  test-e2e-postgresql-geo-api:
    environment:
      API_SERVICE_PORT: ${API_SERVICE_PORT}
      API_UID: ${API_UID}
      API_GID: ${API_GID}
      API_AUTH_JWT_SECRET: ${API_AUTH_JWT_SECRET}
      API_RUN_MIGRATIONS_ON_STARTUP: ${API_RUN_MIGRATIONS_ON_STARTUP}
      API_POSTGRES_USER: ${API_POSTGRES_USER}
      API_POSTGRES_PASSWORD: ${API_POSTGRES_PASSWORD}
      API_POSTGRES_DB: ${API_POSTGRES_DB}
      POSTGRES_API_SERVICE_PORT: ${POSTGRES_API_SERVICE_PORT}
      APP_SERVICE_PORT: ${APP_SERVICE_PORT}
      GEOPROCESSING_SERVICE_PORT: ${GEOPROCESSING_SERVICE_PORT}
      GEOPROCESSING_RUN_MIGRATIONS_ON_STARTUP: ${GEOPROCESSING_RUN_MIGRATIONS_ON_STARTUP}
      GEO_POSTGRES_USER: ${GEO_POSTGRES_USER}
      GEO_POSTGRES_PASSWORD: ${GEO_POSTGRES_PASSWORD}
      GEO_POSTGRES_DB: ${GEO_POSTGRES_DB}
      POSTGRES_GEO_SERVICE_PORT: ${POSTGRES_GEO_SERVICE_PORT}
=======
version: "3.6"
services:
  api:
    environment:
      - API_SERVICE_PORT
      - API_SERVICE_URL
      - API_AUTH_JWT_SECRET
      - API_RUN_MIGRATIONS_ON_STARTUP
      - API_LOGGING_MUTE_ALL
      - API_POSTGRES_USER
      - API_POSTGRES_PASSWORD
      - API_POSTGRES_DB
      - POSTGRES_API_SERVICE_PORT
      - APP_SERVICE_PORT
      - GEOPROCESSING_SERVICE_PORT
      - GEOPROCESSING_RUN_MIGRATIONS_ON_STARTUP
      - GEO_POSTGRES_USER
      - GEO_POSTGRES_PASSWORD
      - GEO_POSTGRES_DB
      - POSTGRES_GEO_SERVICE_PORT
      - REDIS_API_SERVICE_PORT
      - API_AUTH_X_API_KEY

  geoprocessing:
    environment:
      - API_SERVICE_PORT
      - API_SERVICE_URL
      - API_AUTH_JWT_SECRET
      - API_RUN_MIGRATIONS_ON_STARTUP
      - API_LOGGING_MUTE_ALL
      - API_POSTGRES_USER
      - API_POSTGRES_PASSWORD
      - API_POSTGRES_DB
      - POSTGRES_API_SERVICE_PORT
      - APP_SERVICE_PORT
      - GEOPROCESSING_SERVICE_PORT
      - GEOPROCESSING_RUN_MIGRATIONS_ON_STARTUP
      - GEO_POSTGRES_USER
      - GEO_POSTGRES_PASSWORD
      - GEO_POSTGRES_DB
      - POSTGRES_GEO_SERVICE_PORT
      - REDIS_API_SERVICE_PORT
      - API_AUTH_X_API_KEY

  test-e2e-postgresql-api:
    environment:
      - API_SERVICE_PORT
      - API_SERVICE_URL
      - API_AUTH_JWT_SECRET
      - API_RUN_MIGRATIONS_ON_STARTUP
      - API_POSTGRES_USER
      - API_POSTGRES_PASSWORD
      - API_POSTGRES_DB
      - POSTGRES_API_SERVICE_PORT
      - APP_SERVICE_PORT
      - GEOPROCESSING_SERVICE_PORT
      - GEOPROCESSING_RUN_MIGRATIONS_ON_STARTUP
      - GEO_POSTGRES_USER
      - GEO_POSTGRES_PASSWORD
      - GEO_POSTGRES_DB
      - POSTGRES_GEO_SERVICE_PORT
      - REDIS_API_SERVICE_PORT

  test-e2e-postgresql-geo-api:
    environment:
      - API_SERVICE_PORT
      - API_SERVICE_URL
      - API_AUTH_JWT_SECRET
      - API_RUN_MIGRATIONS_ON_STARTUP
      - API_POSTGRES_USER
      - API_POSTGRES_PASSWORD
      - API_POSTGRES_DB
      - POSTGRES_API_SERVICE_PORT
      - APP_SERVICE_PORT
      - GEOPROCESSING_SERVICE_PORT
      - GEOPROCESSING_RUN_MIGRATIONS_ON_STARTUP
      - GEO_POSTGRES_USER
      - GEO_POSTGRES_PASSWORD
      - GEO_POSTGRES_DB
      - POSTGRES_GEO_SERVICE_PORT
      - REDIS_API_SERVICE_PORT

  test-e2e-redis:
    environment:
      - REDIS_API_SERVICE_PORT
>>>>>>> fbf3f123f8cc06fb4b1eda6e3680ba304ca80149
